openapi: 3.0.0
info:
  title: Banking Accounts API - Good Example
  version: 3.0.0
  description: |
    This is a good example of a Banking API that follows best practices for financial services.
    It includes proper descriptions, security, error handling, and compliance with banking standards.

servers:
  - url: https://api.bank.com/v3
    description: Production banking server

paths:
  /accounts:
    get:
      summary: List customer accounts
      description: Retrieve a list of all bank accounts belonging to the authenticated customer.
      operationId: listAccounts
      tags:
        - Accounts
      parameters:
        - name: account_type
          in: query
          description: Filter accounts by type (checking, savings, credit, loan).
          schema:
            type: string
            enum: [checking, savings, credit, loan]
            example: checking
        - name: status
          in: query
          description: Filter accounts by status.
          schema:
            type: string
            enum: [active, frozen, closed]
            default: active
        - name: limit
          in: query
          description: Maximum number of accounts to return (1-50).
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: List of accounts retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - meta
                properties:
                  data:
                    type: array
                    description: Array of bank account objects.
                    items:
                      $ref: '#/components/schemas/Account'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
        '400':
          description: Bad request - Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions to view accounts.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many requests - Rate limit exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [accounts:read]

  /accounts/{accountId}:
    get:
      summary: Get account details
      description: Retrieve detailed information about a specific bank account including balance and account holder information.
      operationId: getAccount
      tags:
        - Accounts
      parameters:
        - name: accountId
          in: path
          required: true
          description: Unique identifier of the bank account.
          schema:
            type: string
            pattern: '^[0-9]{10,16}$'
            example: "1234567890"
      responses:
        '200':
          description: Account details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
        '401':
          description: Unauthorized - Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not authorized to access this account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Account not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [accounts:read]

  /accounts/{accountId}/transactions:
    get:
      summary: Get account transactions
      description: Retrieve a paginated list of transactions for a specific account with optional date range filtering.
      operationId: getAccountTransactions
      tags:
        - Transactions
      parameters:
        - name: accountId
          in: path
          required: true
          description: Unique identifier of the bank account.
          schema:
            type: string
            pattern: '^[0-9]{10,16}$'
        - name: start_date
          in: query
          description: Start date for transaction history (ISO 8601 format).
          schema:
            type: string
            format: date
            example: "2024-01-01"
        - name: end_date
          in: query
          description: End date for transaction history (ISO 8601 format).
          schema:
            type: string
            format: date
            example: "2024-12-31"
        - name: transaction_type
          in: query
          description: Filter by transaction type.
          schema:
            type: string
            enum: [deposit, withdrawal, transfer, payment, fee]
        - name: limit
          in: query
          description: Maximum number of transactions to return (1-100).
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
        - name: offset
          in: query
          description: Number of transactions to skip for pagination.
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Transaction history retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - meta
                properties:
                  data:
                    type: array
                    description: Array of transaction objects.
                    items:
                      $ref: '#/components/schemas/Transaction'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
        '400':
          description: Bad request - Invalid date range or parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not authorized to view transactions for this account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Account not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [transactions:read]

  /transfers:
    post:
      summary: Create fund transfer
      description: Initiate a transfer of funds between accounts. Requires strong customer authentication (SCA) for amounts above threshold.
      operationId: createTransfer
      tags:
        - Transfers
      requestBody:
        required: true
        description: Transfer details including source, destination, and amount.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '201':
          description: Transfer initiated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad request - Invalid transfer data or insufficient funds.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not authorized to transfer from this account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Duplicate transfer or account is frozen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable entity - Transfer failed validation (e.g., exceeds daily limit).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [transfers:write]

components:
  schemas:
    Account:
      type: object
      description: Basic bank account information.
      required:
        - account_id
        - account_number
        - account_type
        - currency_code
        - balance
        - status
      properties:
        account_id:
          type: string
          format: uuid
          description: Unique identifier for the account.
          example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
        account_number:
          type: string
          description: Bank account number (masked for security).
          pattern: '^[0-9]{10,16}$'
          example: "****5678"
        account_type:
          type: string
          description: Type of bank account.
          enum: [checking, savings, credit, loan]
          example: checking
        currency_code:
          type: string
          description: ISO 4217 currency code.
          pattern: '^[A-Z]{3}$'
          example: USD
        balance:
          type: number
          format: double
          description: Current account balance.
          example: 5432.10
        available_balance:
          type: number
          format: double
          description: Available balance for transactions (excluding holds).
          example: 5200.00
        status:
          type: string
          description: Current account status.
          enum: [active, frozen, closed]
          example: active

    AccountDetails:
      allOf:
        - $ref: '#/components/schemas/Account'
        - type: object
          description: Detailed account information including holder details.
          properties:
            account_holder_name:
              type: string
              description: Name of the primary account holder.
              example: John Smith
            iban:
              type: string
              description: International Bank Account Number.
              pattern: '^[A-Z]{2}[0-9]{2}[A-Z0-9]+$'
              example: US89370400440532013000
            swift_code:
              type: string
              description: SWIFT/BIC code for international transfers.
              pattern: '^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$'
              example: BOFAUS3N
            routing_number:
              type: string
              description: Bank routing number (US).
              pattern: '^[0-9]{9}$'
              example: "021000021"
            opened_date:
              type: string
              format: date
              description: Date when the account was opened.
              example: "2020-03-15"
            interest_rate:
              type: number
              format: double
              description: Annual interest rate for savings/credit accounts (percentage).
              example: 2.5
              minimum: 0
            overdraft_limit:
              type: number
              format: double
              description: Overdraft protection limit for checking accounts.
              example: 500.00
              minimum: 0

    Transaction:
      type: object
      description: Bank transaction record.
      required:
        - transaction_id
        - account_id
        - transaction_type
        - amount
        - currency_code
        - transaction_date
        - status
      properties:
        transaction_id:
          type: string
          format: uuid
          description: Unique identifier for the transaction.
          example: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        account_id:
          type: string
          description: Account ID associated with this transaction.
          example: "1234567890"
        transaction_type:
          type: string
          description: Type of transaction.
          enum: [deposit, withdrawal, transfer, payment, fee, interest]
          example: deposit
        amount:
          type: number
          format: double
          description: Transaction amount (positive for credits, negative for debits).
          example: 1250.00
        currency_code:
          type: string
          description: ISO 4217 currency code.
          pattern: '^[A-Z]{3}$'
          example: USD
        description:
          type: string
          description: Human-readable transaction description.
          example: "Salary deposit from Employer Inc"
          maxLength: 255
        transaction_date:
          type: string
          format: date-time
          description: Date and time when transaction was processed.
          example: "2024-12-01T14:30:00Z"
        balance_after:
          type: number
          format: double
          description: Account balance after this transaction.
          example: 6682.10
        status:
          type: string
          description: Current transaction status.
          enum: [pending, completed, failed, reversed]
          example: completed
        reference_number:
          type: string
          description: External reference or check number.
          example: "CHK-20241201-001"

    TransferRequest:
      type: object
      description: Request to transfer funds between accounts.
      required:
        - from_account_id
        - to_account_id
        - amount
        - currency_code
      properties:
        from_account_id:
          type: string
          description: Source account ID.
          pattern: '^[0-9]{10,16}$'
          example: "1234567890"
        to_account_id:
          type: string
          description: Destination account ID.
          pattern: '^[0-9]{10,16}$'
          example: "9876543210"
        amount:
          type: number
          format: double
          description: Amount to transfer (must be positive).
          example: 500.00
          minimum: 0.01
        currency_code:
          type: string
          description: ISO 4217 currency code.
          pattern: '^[A-Z]{3}$'
          example: USD
        description:
          type: string
          description: Optional transfer description or memo.
          example: "Monthly rent payment"
          maxLength: 255
        reference:
          type: string
          description: External reference number.
          example: "INV-2024-001"
          maxLength: 50

    Transfer:
      allOf:
        - $ref: '#/components/schemas/TransferRequest'
        - type: object
          description: Transfer record with status and tracking.
          required:
            - transfer_id
            - status
            - created_at
          properties:
            transfer_id:
              type: string
              format: uuid
              description: Unique identifier for the transfer.
              example: f47ac10b-58cc-4372-a567-0e02b2c3d479
            status:
              type: string
              description: Current transfer status.
              enum: [pending, processing, completed, failed, cancelled]
              example: completed
            created_at:
              type: string
              format: date-time
              description: Timestamp when transfer was initiated.
              example: "2024-12-04T10:15:00Z"
            completed_at:
              type: string
              format: date-time
              description: Timestamp when transfer was completed.
              example: "2024-12-04T10:15:30Z"
              nullable: true

    PaginationMeta:
      type: object
      description: Pagination metadata.
      required:
        - total
        - limit
        - offset
      properties:
        total:
          type: integer
          description: Total number of items matching the query.
          example: 127
        limit:
          type: integer
          description: Maximum number of items returned.
          example: 25
        offset:
          type: integer
          description: Number of items skipped.
          example: 0

    ErrorResponse:
      type: object
      description: Standard error response format for banking API.
      required:
        - code
        - message
        - timestamp
      properties:
        code:
          type: string
          description: Error code for programmatic handling.
          example: INSUFFICIENT_FUNDS
        message:
          type: string
          description: Human-readable error message.
          example: Account does not have sufficient funds for this transfer.
        timestamp:
          type: string
          format: date-time
          description: When the error occurred.
          example: "2024-12-04T10:15:00Z"
        details:
          type: array
          description: Additional error details or field-level validation errors.
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error.
                example: amount
              issue:
                type: string
                description: Description of the issue.
                example: Amount exceeds daily transfer limit of $10,000
        trace_id:
          type: string
          description: Unique trace ID for support and debugging.
          example: "trace-abc123-def456"

  securitySchemes:
    oauth2:
      type: oauth2
      description: OAuth 2.0 authentication with banking scopes.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.bank.com/oauth/authorize
          tokenUrl: https://auth.bank.com/oauth/token
          scopes:
            accounts:read: Read access to account information
            accounts:write: Write access to modify accounts
            transactions:read: Read access to transaction history
            transfers:write: Permission to initiate transfers

security:
  - oauth2: []

tags:
  - name: Accounts
    description: Bank account management operations
  - name: Transactions
    description: Transaction history and details
  - name: Transfers
    description: Fund transfer operations
