openapi: 3.0.3
info:
  title: Bookings API - Microservice Example
  version: 1.0.0
  description: Self-contained bookings microservice API with proper field descriptions.

paths:
  /bookings:
    get:
      summary: List all bookings
      description: Retrieves a paginated list of all bookings for the authenticated user.
      parameters:
        - name: page
          in: query
          description: Page number for pagination, starting from 1.
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Number of items per page, maximum 100.
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: status
          in: query
          description: Filter bookings by status (e.g., pending, confirmed, cancelled).
          schema:
            type: string
            enum: [pending, confirmed, cancelled, completed]
      responses:
        '200':
          description: Successfully retrieved list of bookings.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        booking_id:
                          type: string
                          description: Unique identifier for the booking.
                          example: "bkg_123456"
                        user_id:
                          type: string
                          description: Unique identifier for the user who made the booking.
                          example: "usr_789012"
                        flight_number:
                          type: string
                          description: Flight number for the booking.
                          example: "NZ123"
                        departure_date:
                          type: string
                          format: date-time
                          description: Departure date and time in ISO 8601 format.
                          example: "2025-12-01T10:30:00Z"
                        amount:
                          type: number
                          format: decimal
                          description: Total booking amount in the specified currency.
                          example: 599.99
                        currency_code:
                          type: string
                          pattern: '^[A-Z]{3}$'
                          description: ISO 4217 three-letter currency code.
                          example: "NZD"
                        status:
                          type: string
                          description: Current status of the booking.
                          enum: [pending, confirmed, cancelled, completed]
                          example: "confirmed"
                        created_at:
                          type: string
                          format: date-time
                          description: Timestamp when the booking was created.
                          example: "2025-11-13T09:00:00Z"
                        updated_at:
                          type: string
                          format: date-time
                          description: Timestamp when the booking was last updated.
                          example: "2025-11-13T10:15:00Z"
                  meta:
                    type: object
                    description: Pagination metadata for the response.
                    properties:
                      total:
                        type: integer
                        description: Total number of bookings available.
                        example: 150
                      page:
                        type: integer
                        description: Current page number.
                        example: 1
                      per_page:
                        type: integer
                        description: Number of items per page.
                        example: 20
                      total_pages:
                        type: integer
                        description: Total number of pages available.
                        example: 8
        '400':
          description: Bad request due to invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Human-readable error message explaining the issue.
                    example: "Invalid query parameters provided."
                  code:
                    type: string
                    description: Machine-readable error code for client handling.
                    example: "BAD_REQUEST"
                  timestamp:
                    type: string
                    format: date-time
                    description: Timestamp when the error occurred.
                    example: "2025-11-13T10:30:00Z"
        '401':
          description: Unauthorized access due to missing or invalid authentication.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Human-readable error message.
                    example: "Authentication required."
                  code:
                    type: string
                    description: Machine-readable error code.
                    example: "UNAUTHORIZED"
        '500':
          description: Internal server error occurred while processing the request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Human-readable error message.
                    example: "An internal error occurred."
                  code:
                    type: string
                    description: Machine-readable error code.
                    example: "INTERNAL_ERROR"

    post:
      summary: Create a new booking
      description: Creates a new booking with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - flight_number
                - departure_date
                - passenger_details
              properties:
                flight_number:
                  type: string
                  description: Flight number for the new booking.
                  example: "NZ456"
                departure_date:
                  type: string
                  format: date-time
                  description: Preferred departure date and time.
                  example: "2025-12-15T14:00:00Z"
                passenger_details:
                  type: object
                  description: Details of the passenger making the booking.
                  properties:
                    name:
                      type: string
                      description: Full name of the passenger.
                      example: "John Doe"
                    email:
                      type: string
                      format: email
                      description: Email address for booking confirmation.
                      example: "john.doe@example.com"
                    phone:
                      type: string
                      description: Contact phone number for the passenger.
                      example: "+64 21 123 4567"
      responses:
        '201':
          description: Booking successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: string
                    description: Unique identifier for the newly created booking.
                    example: "bkg_987654"
                  status:
                    type: string
                    description: Initial status of the booking.
                    example: "pending"
                  created_at:
                    type: string
                    format: date-time
                    description: Timestamp when the booking was created.
                    example: "2025-11-13T10:45:00Z"
        '400':
          description: Invalid request body or missing required fields.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message explaining validation failures.
                    example: "Missing required field: passenger_details."
                  code:
                    type: string
                    description: Error code for the validation failure.
                    example: "VALIDATION_ERROR"

  /bookings/{bookingId}:
    get:
      summary: Get booking details
      description: Retrieves detailed information for a specific booking by ID.
      parameters:
        - name: bookingId
          in: path
          required: true
          description: Unique identifier of the booking to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved booking details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: string
                    description: Unique identifier for the booking.
                    example: "bkg_123456"
                  user_id:
                    type: string
                    description: Unique identifier for the user.
                    example: "usr_789012"
                  status:
                    type: string
                    description: Current booking status.
                    example: "confirmed"
                  amount:
                    type: number
                    description: Total booking amount.
                    example: 599.99
                  currency_code:
                    type: string
                    description: ISO 4217 currency code.
                    example: "NZD"
        '404':
          description: Booking not found with the specified ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating booking not found.
                    example: "Booking not found."
                  code:
                    type: string
                    description: Error code for not found.
                    example: "NOT_FOUND"

# Note: This is a self-contained microservice API spec
# - All fields defined inline (no external dependencies)
# - Common fields follow recommended patterns
# - Every field has proper description with punctuation
# - Ready for independent deployment and evolution
