openapi: 3.0.0
info:
  title: Employee Management API - Good Example
  version: 2.0.0
  description: |
    This is a good example of an Employee Management API that follows best practices.
    It includes proper descriptions, common fields, error responses, and security.

servers:
  - url: https://api.company.com/v2
    description: Production server

paths:
  /employees:
    get:
      summary: List all employees
      description: Retrieve a paginated list of employees with optional filtering by department, status, and search query.
      operationId: listEmployees
      tags:
        - Employees
      parameters:
        - name: department
          in: query
          description: Filter employees by department name.
          schema:
            type: string
            example: Engineering
        - name: status
          in: query
          description: Filter employees by employment status.
          schema:
            type: string
            enum: [active, on_leave, terminated]
            example: active
        - name: search
          in: query
          description: Search employees by name or email.
          schema:
            type: string
            example: john.doe
        - name: limit
          in: query
          description: Maximum number of employees to return (1-100).
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of employees to skip for pagination.
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successfully retrieved list of employees.
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - meta
                properties:
                  data:
                    type: array
                    description: Array of employee objects.
                    items:
                      $ref: '#/components/schemas/Employee'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
        '400':
          description: Bad request - Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions to view employees.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

    post:
      summary: Create new employee
      description: Create a new employee record in the system with required personal and employment information.
      operationId: createEmployee
      tags:
        - Employees
      requestBody:
        required: true
        description: Employee data for creation.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
      responses:
        '201':
          description: Employee successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad request - Invalid employee data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions to create employees.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Employee with this email already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /employees/{employeeId}:
    get:
      summary: Get employee details
      description: Retrieve detailed information about a specific employee by their ID.
      operationId: getEmployee
      tags:
        - Employees
      parameters:
        - name: employeeId
          in: path
          required: true
          description: Unique identifier of the employee.
          schema:
            type: string
            format: uuid
            example: 550e8400-e29b-41d4-a716-446655440000
      responses:
        '200':
          description: Employee details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '401':
          description: Unauthorized - Invalid or missing authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions to view this employee.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

    patch:
      summary: Update employee
      description: Update specific fields of an employee record. Only provided fields will be updated.
      operationId: updateEmployee
      tags:
        - Employees
      parameters:
        - name: employeeId
          in: path
          required: true
          description: Unique identifier of the employee.
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: Employee fields to update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeUpdate'
      responses:
        '200':
          description: Employee updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad request - Invalid update data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions to update this employee.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

components:
  schemas:
    Employee:
      type: object
      description: Complete employee information including personal and employment details.
      required:
        - employee_id
        - first_name
        - last_name
        - email
        - department
        - position
        - employment_status
        - hire_date
      properties:
        employee_id:
          type: string
          format: uuid
          description: Unique identifier for the employee.
          example: 550e8400-e29b-41d4-a716-446655440000
        first_name:
          type: string
          description: Employee's first name.
          example: John
          minLength: 1
          maxLength: 50
        last_name:
          type: string
          description: Employee's last name.
          example: Doe
          minLength: 1
          maxLength: 50
        email:
          type: string
          format: email
          description: Employee's work email address.
          example: john.doe@company.com
        phone:
          type: string
          description: Employee's contact phone number.
          example: +1-555-123-4567
          pattern: '^\+?[1-9]\d{1,14}$'
        department:
          type: string
          description: Department where the employee works.
          example: Engineering
        position:
          type: string
          description: Employee's job title or position.
          example: Senior Software Engineer
        employment_status:
          type: string
          description: Current employment status.
          enum: [active, on_leave, terminated]
          example: active
        hire_date:
          type: string
          format: date
          description: Date when the employee was hired (ISO 8601 format).
          example: 2020-01-15
        salary:
          type: number
          format: double
          description: Annual salary in USD.
          example: 95000.00
          minimum: 0
        manager_id:
          type: string
          format: uuid
          description: Employee ID of the direct manager.
          example: 660e8400-e29b-41d4-a716-446655440001
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Timestamp when the employee record was created.
          example: 2020-01-15T10:30:00Z
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the employee record was last updated.
          example: 2024-12-01T14:20:00Z

    EmployeeCreate:
      type: object
      description: Data required to create a new employee.
      required:
        - first_name
        - last_name
        - email
        - department
        - position
        - hire_date
      properties:
        first_name:
          type: string
          description: Employee's first name.
          example: Jane
        last_name:
          type: string
          description: Employee's last name.
          example: Smith
        email:
          type: string
          format: email
          description: Employee's work email address.
          example: jane.smith@company.com
        phone:
          type: string
          description: Employee's contact phone number.
          example: +1-555-987-6543
        department:
          type: string
          description: Department where the employee will work.
          example: Marketing
        position:
          type: string
          description: Employee's job title or position.
          example: Marketing Manager
        hire_date:
          type: string
          format: date
          description: Date when the employee starts working.
          example: 2024-12-15
        salary:
          type: number
          format: double
          description: Annual salary in USD.
          example: 85000.00
        manager_id:
          type: string
          format: uuid
          description: Employee ID of the direct manager.
          example: 660e8400-e29b-41d4-a716-446655440001

    EmployeeUpdate:
      type: object
      description: Fields that can be updated for an employee. All fields are optional.
      properties:
        first_name:
          type: string
          description: Employee's first name.
          example: John
        last_name:
          type: string
          description: Employee's last name.
          example: Doe
        email:
          type: string
          format: email
          description: Employee's work email address.
          example: john.doe@company.com
        phone:
          type: string
          description: Employee's contact phone number.
          example: +1-555-123-4567
        department:
          type: string
          description: Department where the employee works.
          example: Engineering
        position:
          type: string
          description: Employee's job title or position.
          example: Lead Software Engineer
        employment_status:
          type: string
          description: Current employment status.
          enum: [active, on_leave, terminated]
          example: active
        salary:
          type: number
          format: double
          description: Annual salary in USD.
          example: 105000.00
        manager_id:
          type: string
          format: uuid
          description: Employee ID of the direct manager.
          example: 660e8400-e29b-41d4-a716-446655440001

    PaginationMeta:
      type: object
      description: Pagination metadata for list responses.
      required:
        - total
        - limit
        - offset
      properties:
        total:
          type: integer
          description: Total number of employees matching the query.
          example: 150
        limit:
          type: integer
          description: Maximum number of employees returned in this response.
          example: 20
        offset:
          type: integer
          description: Number of employees skipped.
          example: 0

    ErrorResponse:
      type: object
      description: Standard error response format.
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code for programmatic error handling.
          example: EMPLOYEE_NOT_FOUND
        message:
          type: string
          description: Human-readable error message.
          example: Employee with ID 550e8400-e29b-41d4-a716-446655440000 not found.
        details:
          type: array
          description: Additional error details or validation errors.
          items:
            type: object
            properties:
              field:
                type: string
                description: Field name that caused the error.
                example: email
              issue:
                type: string
                description: Description of the issue.
                example: Email format is invalid

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from the authentication service.

security:
  - bearerAuth: []

tags:
  - name: Employees
    description: Employee management operations
